# Generated by Django 4.1 on 2022-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Department_Name', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
